url: https://theratelecom.github.io
baseurl: /theratelecom.github.io/

# Site settings
title: Thera Telecom
email: suporte@thera.net.br
description: Conectando negócios

logo: true

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
